/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --no-audit 
Author: Feyfolken-Km (https://sketchfab.com/Feyfolken-Km)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/asset-by-feyfolken-food-props-apple-304381475f2e400ebbcabfe14eac8b34
Title: Asset by Feyfolken | Food Props | Apple
*/

import { Outlines, useGLTF } from '@react-three/drei';
import { DoubleSide } from 'three';

export default function Apple(props) {
    const { nodes, materials } = useGLTF('./apple/scene.gltf');

    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.Apple_0.geometry} rotation={[-Math.PI / 2, 0, 0]}>
                <meshStandardMaterial map={materials.Apple.map} color={'#d4d4d4'} side={DoubleSide} />
                <Outlines screenspace thickness={0.002} />
            </mesh>
        </group>
    );
}

useGLTF.preload('./apple/scene.gltf');
